# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e59ee6729438b203fa1bf48d616e9835fbafe0822a5bb73656eea813ed4a1e4b0643d086a94ac3c98b72f9976538e3e534f68ec8e1c5937a18e626d0427dcc3c

test:
  secret_key_base: 4623433a78e183dcfc5cd5ea2ca0e269f9bb132b46e933af40ce199b665ae6d24a76b29db56558564feda46410e27558f310e59ca35d1773fe7f89d81344e9fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
